version: "3.3"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env

  app:
    image: myshop:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
    env_file:
      - env
   

  nginx:
    image: nginx
    volumes:
      - media:/media/
      - static:/static/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8000:8000
    depends_on:
      - app

volumes:
  postgres_data:
  media:
  static: