# Generated by Django 4.1.1 on 2023-05-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
