# Generated by Django 4.1.1 on 2023-05-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
