# Generated by Django 4.1.1 on 2023-05-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_category_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
